client: client.cpp
	g++ client.cpp -I/home/jun/Documents/Project/lib/unpv13e/lib -g -Wall -std=c++11 -lpthread 
.PHONY: debug

debug:
	g++ client.cpp -I/home/jun/Documents/Project/lib/unpv13e/lib -g -Wall -std=c++11 -lpthread -D _DEBUG

